disp('24th May 2016, night run');
clear all;
%simulation_workframe5;
results = load('sim_5');
results = results.library_report;
mx1.area = [];
mx1.pop = [];
mx2.area = [];
mx2.pop = [];
mx3.area = [];
mx3.pop = [];
diversity = [];
for iter = 1 : 1 : length(results);
	mx1.area(:,iter) = results(iter).hist_area(:, 1);
	mx2.area(:,iter) = results(iter).hist_area(:, 2);
	mx3.area(:,iter) = results(iter).hist_area(:, 3);
	mx1.pop(:, iter) = results(iter).hist_pop(:,1);
	mx2.pop(:, iter) = results(iter).hist_pop(:,2);
	mx3.pop(:, iter) = results(iter).hist_pop(:,3);
	diversity(iter,:) = [results(iter).genotype_composition];
end
x = [];
y = [];
z1 = [];
z2 = [];
z3 = [];
z4 = [];
z5 = [];
division_val = 0.1;
for iter = 1 : 1 : length(results);
	lplus = diversity(iter,1)*(diversity(iter, 1) > 0) + (diversity(iter,1) == 0);
	l3 = diversity(iter,2)*(diversity(iter, 2) > 0) + (diversity(iter,2) == 0);
	l4 = diversity(iter,3);
	x(iter) = floor(lplus/division_val) + 1 ;
	y(iter) = floor(l3/division_val) + 1	;
	z1(iter, 1) = mx1.area(150, iter)/(2500*lplus);
	z2(iter, 1) = mx1.area(300, iter)/(2500*lplus);
	z3(iter, 1) = mx1.area(450, iter)/(2500*lplus);
	z4(iter, 1) = mx1.area(600, iter)/(2500*lplus);
	z5(iter, 1) = mx1.area(750, iter)/(2500*lplus);
	z1(iter, 2) = mx2.area(150, iter)/(2500*lplus);
	z2(iter, 2) = mx2.area(300, iter)/(2500*lplus);
	z3(iter, 2) = mx2.area(450, iter)/(2500*lplus);
	z4(iter, 2) = mx2.area(600, iter)/(2500*lplus);
	z5(iter, 2) = mx2.area(750, iter)/(2500*lplus);
	z1(iter, 3) = mx3.area(150, iter)/(2500*(lplus + l3));
	z2(iter, 3) = mx3.area(300, iter)/(2500*(lplus + l3));
	z3(iter, 3) = mx3.area(450, iter)/(2500*(lplus + l3));
	z4(iter, 3) = mx3.area(600, iter)/(2500*(lplus + l3));
	z5(iter, 3) = mx3.area(750, iter)/(2500*(lplus + l3));
end
for yiter = 1 : 1: (1/division_val);
	for xiter = 1 : 1 : (1/division_val);
		x_ensamble = [x == xiter];
		y_ensamble = [y == yiter];
		current_values = (x_ensamble .* y_ensamble);
		current_values = find(current_values);
		if sum(current_values) == 0
			z1_av(xiter, yiter, 1) = 0;
			z1_av(xiter, yiter, 2) = 0;
			z1_av(xiter, yiter, 3) = 0;
			z2_av(xiter, yiter, 1) = 0;
			z2_av(xiter, yiter, 2) = 0;
			z2_av(xiter, yiter, 3) = 0;
			z3_av(xiter, yiter, 1) = 0;
			z3_av(xiter, yiter, 2) = 0;
			z3_av(xiter, yiter, 3) = 0;
			z4_av(xiter, yiter, 1) = 0;
			z4_av(xiter, yiter, 2) = 0;
			z4_av(xiter, yiter, 3) = 0;
			z5_av(xiter, yiter, 1) = 0;
			z5_av(xiter, yiter, 2) = 0;
			z5_av(xiter, yiter, 3) = 0;
			z1_t(xiter, yiter) = 0;
			z2_t(xiter, yiter) = 0;
			z3_t(xiter, yiter) = 0;
			z4_t(xiter, yiter) = 0;
			z5_t(xiter, yiter) = 0;
		else
			z1_av(xiter, yiter,1) = mean(z1(current_values, 1));

			z1_av(xiter, yiter, 2) = mean(z1(current_values, 2));
			z1_av(xiter, yiter, 3) = mean(z1(current_values, 3));
			z1_t(xiter, yiter) = sum(z1_av(xiter, yiter,:));
			z2_av(xiter, yiter,1) = mean(z2(current_values, 1));
			z2_av(xiter, yiter, 2) = mean(z2(current_values, 2));
			z2_av(xiter, yiter, 3) = mean(z2(current_values, 3));
			z2_t(xiter, yiter) = sum(z2_av(xiter, yiter,:));
			z3_av(xiter, yiter,1) = mean(z3(current_values, 1));
			z3_av(xiter, yiter, 2) = mean(z3(current_values, 2));
			z3_av(xiter, yiter, 3) = mean(z3(current_values, 3));
			z3_t(xiter, yiter) = sum(z3_av(xiter, yiter,:));
			z4_av(xiter, yiter,1) = mean(z4(current_values, 1));
			z4_av(xiter, yiter, 2) = mean(z4(current_values, 2));
			z4_av(xiter, yiter, 3) = mean(z4(current_values, 3));
			z4_t(xiter, yiter) = sum(z4_av(xiter, yiter,:));
			z5_av(xiter, yiter,1) = mean(z5(current_values, 1));
			z5_av(xiter, yiter, 2) = mean(z5(current_values, 2));
			z5_av(xiter, yiter, 3) = mean(z5(current_values, 3));
			z5_t(xiter, yiter) = sum(z5_av(xiter, yiter,:));
		end
	end
end
